[project]
authors = ["Rhys Newell <rhys.newell94@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "aviary"
platforms = ["linux-64"]

[activation]
# Sets metapackage environment variables, which are assumed to be in the db/ of
# the base directory (perhaps symlnked).
scripts = ["set_env_vars.sh"]

[feature.main.dependencies]
python = ">=3.8,<=3.11"
snakemake = ">=7.0.0,<=7.32.3"
"ruamel.yaml" = ">=0.15.99"
numpy = "*"
pandas = "*"
biopython = "*"
pigz = ">=2.6"
parallel = "*"
extern = "*"
pyopenssl = ">22.1.0"
pixi = "*"
pip = "*"

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e .."
update_deps = { cmd = "python ../admin/build_dep_defs_from_pixi.py", depends-on = ["postinstall"] }

[feature.dev.dependencies]
pytest = "*"
ipython = "*"
toml = "*"
bird_tool_utils_python = "*"

[environments]
default = ["main"]
dev = ["dev", "main"]
# Overall environments
metabuli = ['metabuli']
singlem = ['singlem']
# QC
chopper = ["chopper"]
fastqc = ["fastqc"]
nanoplot = ["nanoplot"]
quast = ["quast"]
bbmap = ["bbmap"]
# Assembly
flye = ["flye"]
polishing = ["polishing"]
pilon = ["pilon"]
minimap2 = ["minimap2"]
spades = ["spades"]
pysam = ["pysam"]
# Binning
seqkit = ["seqkit"]
metabat2 = ["metabat2"]
checkm = ["checkm"]
checkm2 = ["checkm2"]
coverm = ["coverm"]
das-tool = ["das-tool"]
rosella = ["rosella"]
maxbin2 = ["maxbin2"]
concoct = ["concoct"]
vamb = ["vamb"]
taxvamb = ["vamb"]
taxvamb-gpu = ["vamb", "vamb-gpu"]
semibin = ["semibin"]
semibin-gpu = ["semibin","semibin-gpu"]
comebin = ["comebin"]
comebin-gpu = ["comebin", "comebin-gpu"]
eggnog = ["eggnog"]
gtdbtk = ["gtdbtk"]

[feature.metabuli.dependencies]
metabuli = "~=1.0.0"

[feature.singlem.dependencies]
singlem = ">=0.16.0"

[feature.singlem.pypi-dependencies]
bird-tool-utils = "*"

[feature.chopper.dependencies]
chopper = ">=0.6"
pigz = '*'

[feature.fastqc.dependencies]
fastqc = "==0.11.9"

[feature.nanoplot.dependencies]
# Min 1.44 to fix https://github.com/rhysnewell/aviary/issues/272
nanoplot = ">=1.44"

[feature.quast.dependencies]
quast = "==5.0.2"

[feature.bbmap.dependencies]
bbmap = "*"

[feature.flye.dependencies]
flye = ">=2.9"

[feature.polishing.dependencies]
flye = ">=2.9"
medaka = ">=1.7.2"
setuptools = "*"
racon = ">=1.4.3"
samtools = ">=1.16"
minimap2 = ">=2.15"
seqkit = "=2.1"
pigz = "*"

[feature.pilon.dependencies]
python = ">=3.6"
flye = ">=2.9"
medaka = ">=1.7.2"
racon = ">=1.4.3"
samtools = ">=1.9"
minimap2 = ">=2.15"
seqkit = "=2.1"
pigz = "*"
pilon = ">=1.23"

[feature.minimap2.dependencies]
samtools = "=1.9"
minimap2 = "=2.18"
fastp = "*"
pigz = "*"

[feature.spades.dependencies]
python = "=3.12.0"  # Keep things consistent to aid debugging.
spades = "=4.0.0"
megahit = "=1.2.9"
pyyaml = "=6.0.2"
joblib = "=1.4.2"

[feature.pysam.dependencies]
python = ">=3.6"
pysam = "=0.16"

[feature.seqkit.dependencies]
seqkit = "*"

[feature.metabat2.dependencies]
metabat2 = ">=2.15"

[feature.checkm.dependencies]
"checkm-genome" = ">=1.1.2"
parallel = "*"
setuptools = "*"

[feature.checkm2.dependencies]
checkm2 = "=1.1.0"

[feature.coverm.dependencies]
coverm = ">=0.6"
galah = ">=0.3"
chopper = ">=0.6"
pigz = "*"
parallel = "*"
dashing = "*"
fastani = "*"

[feature.das-tool.dependencies]
das_tool = "=1.1.2"
extern = "=0.4.1"

[feature.rosella.dependencies]
rosella = ">=0.5.3"
flight-genome = ">=1.6.3"
coverm = ">=0.6.1"
checkm-genome = "=1.1.3"

[feature.maxbin2.dependencies]
maxbin2 = ">=2.2.7"
perl = ">=5.22.0"
perl-lwp-simple = "*"

[feature.concoct.dependencies]
scikit-learn = ">=1.1.0"
concoct = "==1.1.0"

[feature.vamb.dependencies]
samtools = "*"
vamb = "5.0.*"

[feature.vamb-gpu]
system-requirements = { cuda = "12.1" }
channels = ["pytorch", "nvidia"]

[feature.vamb-gpu.dependencies]
pytorch-gpu = "*"

[feature.semibin.dependencies]
semibin = "2.1.*"

[feature.semibin-gpu]
system-requirements = { cuda = "12.1" }

[feature.semibin-gpu.dependencies]
pytorch-gpu = "*"

[feature.comebin.dependencies]
comebin = "1.0.*"

[feature.comebin-gpu]
system-requirements = { cuda = "11.8" }
channels = ["nvidia", "pytorch"]
channel-priority = "disabled"

[feature.comebin-gpu.dependencies]
pytorch = { version = "==1.10.2", channel = "pytorch" }
pytorch-cuda = { version = "==11.8", channel = "pytorch" }
mkl = "==2024.0"

[feature.eggnog.dependencies]
eggnog-mapper =  ">=2.1.8"
parallel = "*"

[feature.gtdbtk.dependencies]
gtdbtk = "==2.4.0"
fastani = "*"
