from snakemake.utils import min_version
min_version("6.0")


if config["assembly"] == "none":
	module assembly:
	    snakefile: "assembly/Snakefile"
	    config: config

	use rule * from assembly as *

	config["assembly"] = "data/final_contigs.fasta"


module binning:
    snakefile: "binning/Snakefile"
    config: config 
    
use rule * from binning as *


