name: Deploy documentation site

on:
  push:
    branches:
      - main
      - update_doc
    paths:
      - 'docs/**'
      - 'doctave.yaml'
  workflow_dispatch:

jobs:
  build:
    name: Deploys
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Setup homebrew'
      uses: Homebrew/actions/setup-homebrew@master

    - name: 'Build and deploy'
      shell: bash
      run: |
        brew install doctave/doctave/doctave
        doctave build --release --allow-failed-checks
        touch site/.nojekyll

    - name: GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/update_doc'
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        build_dir: site/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}